version: '3.1'

services:
  mysql:
    image: mysql:8.0.27
    container_name: mysql58
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test-db-prisma
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: